# .circleci/config.yml
version: 2

orbs:
  ruby: circleci/ruby@3.1.2
  node: circleci/node@16.17.1
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build:
    docker:
      - image: circleci/ruby:3.1.2
    environment:
        RAILS_ENV: development
  steps:
    - checkout

    # Setup the environment
    # - run: cp .sample.env .env

    # Run the tests
    - run: exec bundle install