version: '2'

orbs:
  ruby: circleci/ruby@3.1.2

jobs:
  build:
    docker:
      - image: 'cimg/ruby:3.1.2'
        # environment:
        #   PGHOST: localhost
        #   PGUSER: Scraper
        #   RAILS_ENV: development
    steps:
      - checkout
      - run: bundle install
workflows:
  build:
    jobs:
      - build
