
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV['DATABASE']%>
  username: <%= ENV['USER_NAME']%>
  password: <%= ENV['PASSWORD']%>
  host: <%= ENV['HOST']%>


test:
  <<: *default
  database: <%= ENV["DATABASE"]%>
  username: <%= ENV["USER_NAME"]%>
  password: <%= ENV["PASSWORD"]%>
  host: <%= ENV["HOST"]%>



production:
  <<: *default
  database: <%= ENV["DATABASE"]%>
  username: <%= ENV["USER_NAME"]%>
  password: <%= ENV["PASSWORD"]%>
